version: "3.3"

secrets:
  transip_private_key:
    file: "./secrets/transip_private_key.secret"

services:

  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    restart: unless-stopped
    secrets:
      - "transip_private_key"
    environment:
      - "TRANSIP_ACCOUNT_NAME=skardoska"
      - "TRANSIP_PRIVATE_KEY_PATH=/run/secrets/transip_private_key"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
     # - "--certificatesresolvers.myresolver.acme.acmelogging=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=transip"
     # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=mail@koenjanssen.xyz"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.dnsChallenge.resolvers=1.1.1.1:53,8.8.8.8:53"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "./letsencrypt:/letsencrypt"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.koen.link`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=*****************"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.koen.link`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=koen.link"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.koen.link"
      - "traefik.http.routers.traefik-secure.service=api@internal"
  
  nginx_portfolio:
    image: "nginx"
    container_name: "portfolio"
    restart: unless-stopped
#    environment:
    #  - NGINX_HOST=web.koen.link
     # - NGINX_PORT=80
    volumes:
      - /srv/www/portfolio/html:/usr/share/nginx/html:z
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.portfolio.compress=true"
      - "traefik.http.routers.portfolio.entrypoints=http"
      - "traefik.http.routers.portfolio.rule=Host(`koen.link`)"
      - "traefik.http.middlewares.portfolio-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.portfolio.middlewares=portfolio-https-redirect"
      - "traefik.http.routers.portfolio-secure.entrypoints=https"
      - "traefik.http.routers.portfolio-secure.rule=Host(`koen.link`)"
      - "traefik.http.routers.portfolio-secure.tls=true"
      - "traefik.http.routers.portfolio-secure.tls.certresolver=myresolver"
      #- "traefik.http.routers.portfolio-secure.tls.options..minVersion=VersionTLS12"
 
  nginx_portfolio_xyz:
    image: "nginx"
    container_name: "portfolio_xyz"
    restart: unless-stopped
   # environment:
    #  - NGINX_HOST=web.koen.link
     # - NGINX_PORT=80
    volumes:
      - /srv/www/portfolio/html:/usr/share/nginx/html:z
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio_xyz.entrypoints=http"
      - "traefik.http.routers.portfolio_xyz.rule=Host(`koenjanssen.xyz`)"
      - "traefik.http.middlewares.portfolio_xyz-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.portfolio_xyz.middlewares=portfolio_xyz-https-redirect"
      - "traefik.http.routers.portfolio_xyz-secure.entrypoints=https"
      - "traefik.http.routers.portfolio_xyz-secure.rule=Host(`koenjanssen.xyz`)"
      - "traefik.http.routers.portfolio_xyz-secure.tls=true"
      - "traefik.http.routers.portfolio_xyz-secure.tls.certresolver=myresolver"
      - "traefik.http.routers.portfolio_xyz-secure.tls.domains[0].main=koenjanssen.xyz"
      - "traefik.http.routers.portfolio_xyz-secure.tls.domains[0].sans=*.koenjanssen.xyz"

  nc:
    image: "nextcloud"
    container_name: "nc"
    restart: unless-stopped
    environment:
     # - NEXTCLOUD_ADMIN_USER=koen
     # - NEXTCLOUD_ADMIN_PASSWORD=*****************
     # - NEXTCLOUD_TRUSTED_DOMAINS=nc.koen.link
      - MYSQL_DATABASE=*****************
      - MYSQL_USER=*****************
      - MYSQL_PASSWORD=*****************
      - MYSQL_HOST=*****************
      #- POSTGRES_DB=*****************
      #- POSTGRES_USER=*****************
      #- POSTGRES_PASSWORD=*****************
      #- POSTGRES_HOST=*****************
      - REDIS_HOST=*****************
      - REDIS_HOST_PORT=*****************
      - REDIS_HOST_PASSWORD=*****************
    volumes:
      - /srv/nc/nextcloud:/var/www/html:rw
      - /srv/nc/apps:/var/www/html/custom_apps:rw
      - /srv/nc/config:/var/www/html/config:rw
      - /srv/nc/data:/var/www/html/data:rw
      #- /srv/nc/apache2:/etc/apache2:rw
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.nextcloud-caldav.redirectregex.permanent=true"
      - "traefik.http.middlewares.nextcloud-caldav.redirectregex.regex=^https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nextcloud-caldav.redirectregex.replacement=https://$${1}/remote.php/dav/"
      - "traefik.http.routers.nc.entrypoints=http"
      - "traefik.http.routers.nc.rule=Host(`nc.koen.link`)"
      - "traefik.http.middlewares.nc-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.nc.middlewares=nc-https-redirect"
      - "traefik.http.routers.nc-secure.entrypoints=https"
      - "traefik.http.routers.nc-secure.rule=Host(`nc.koen.link`)"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-caldav@docker"
      - "traefik.http.routers.nc-secure.tls=true"
      - "traefik.http.routers.nc-secure.tls.certresolver=myresolver"
      #- "traefik.http.routers.nc.middlewares=nc@docker"

 # nc_db2:
 #   image: "postgres"
 #   restart: unless-stopped
 #   container_name: "nc_db2"
 ##     - "/srv/nc_postgres:/var/lib/postgresql/data/pgdata"
 #   environment:
 #     - POSTGRES_USER=postgres
 #     - POSTGRES_PASSWORD=*****************
 #     - PGDATA=/var/lib/postgresql/data/pgdata
      

  nc_db:
    image: "mariadb"
    container_name: "nc_db"
    restart: unless-stopped
   # command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    volumes:
      - /srv/nc_db/config:/var/lib/mysql:rw
     # - ./custom_mariadb/mariadb.cnf:/config/custom.cnf
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=*****************
      - TZ=Europe/Amsterdam
      - MYSQL_DATABASE=*****************
      - MYSQL_USER=*****************
      - MYSQL_PASSWORD=*****************
    labels:
      - "traefik.enable=true"

  redis:
    image: "redis"
    container_name: "nc_redis"
    restart: unless-stopped
    volumes:
      - /srv/nc_redis/mysql:/var/lib/mysql:rw
    environment:
      - REDIS_PASSWORD=***************** redis sh -c 'exec redis-server --requirepass "$REDIS_PASSWORD"'
    labels:
      - "traefik.enable=true"

  #gitlab:
  #  image: "ulm0/gitlab"
  #  container_name: "gitlab"
  #  restart: unless-stopped
  #  hostname: "gtl.koen.link"
  #  environment:
  #    GITLAB_OMNIBUS_CONFIG: |
  #      external_url 'http://gtl.koen.link'
  #      nginx['listen_port'] = 80  
  #      # Add any other gitlab.rb configuration here, each on its own line
  #  ports:
  #    - "2222:22"
  #  volumes:
  #    - /srv/gitlab/config:/etc/gitlab:rw
  #    - /srv/gitlab/logs:/var/log/gitlab:rw
  #    - /srv/gitlab/data:/var/opt/gitlab:rw
  #  labels:
  #    - "traefik.enable=true"
  #    - "traefik.http.routers.gitlab.entrypoints=http"
  #    - "traefik.http.routers.gitlab.rule=Host(`gtl.koen.link`)"
  #    - "traefik.http.middlewares.gitlab-https-redirect.redirectscheme.scheme=https"
  #    - "traefik.http.routers.gitlab.middlewares=gitlab-https-redirect"
  #   - "traefik.http.routers.gitlab-secure.entrypoints=https"
  #    - "traefik.http.routers.gitlab-secure.rule=Host(`gtl.koen.link`)"
  #    - "traefik.http.services.gitlab.loadbalancer.server.port=80"
  #    - "traefik.http.routers.gitlab-secure.tls=true"
  #    - "traefik.http.routers.gitlab-secure.tls.certresolver=myresolver"


  gitea-web:
    image: gitea/gitea:1.6
    restart: always
    volumes:
      - /srv/gitea/data/:/data
    expose:
      - "3000"
    ports:
      #- "3080:3000"
      - "2222:22"
    depends_on:
      - gitea-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`git.koen.link`)"
      - "traefik.http.routers.gitea.entrypoints=http"
      - "traefik.http.middlewares.gitea-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.gitea.middlewares=gitea-https-redirect"
      - "traefik.http.routers.gitea-secure.entrypoints=https"
      - "traefik.http.routers.gitea-secure.rule=Host(`git.koen.link`)"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
      - "traefik.http.routers.gitea-secure.tls=true"
      - "traefik.http.routers.gitea-secure.tls.certresolver=myresolver"
    environment:
      - USER_UID=1000
      - USER_GID=1000   
      - DB_TYPE=mysql
      - DB_HOST=*****************
      - DB_NAME=*****************
      - DB_USER=*****************
      - DB_PASSWD=*****************
      - HTTP_PORT=3000
   
  gitea-db:
    image: mariadb:10
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=*****************
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=*****************
    volumes:
      - /srv/gitea/db/:/var/lib/mysql
    labels:
      - "traefik.enable=true"

