version: "3.3"

secrets:
  transip_private_key:
    file: "./secrets/transip_private_key.secret"

services:

  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    restart: unless-stopped
    secrets:
      - "transip_private_key"
    environment:
      - "TRANSIP_ACCOUNT_NAME="
      - "TRANSIP_PRIVATE_KEY_PATH=/run/secrets/transip_private_key"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
     # - "--entrypoints.mc.address=217.182.216.255:25663/tcp"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
     # - "--certificatesresolvers.myresolver.acme.acmelogging=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=transip"
     # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email="
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.dnsChallenge.resolvers=1.1.1.1:53,8.8.8.8:53"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "./letsencrypt:/letsencrypt"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.koen.link`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=test:pwdhere"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.koen.link`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=myresolver"
      #- "traefik.http.routers.traefik-secure.tls.domains[0].main=koen.link"
      #- "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.koen.link"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      #- "traefik.http.routers.traefik-secure.entrypoints=mc"

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    container_name: "phpmyadmin"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.phpmyadmin.compress=true"
      - "traefik.http.routers.phpmyadmin.entrypoints=http"
      - "traefik.http.routers.phpmyadmin.rule=Host(`pma.koen.link`)"
      - "traefik.http.middlewares.phpmyadmin-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.phpmyadmin.middlewares=phpmyadmin-https-redirect"
      - "traefik.http.routers.phpmyadmin-secure.entrypoints=https"
      - "traefik.http.routers.phpmyadmin-secure.rule=Host(`pma.koen.link`)"
      - "traefik.http.routers.phpmyadmin-secure.tls=true"
      - "traefik.http.routers.phpmyadmin-secure.tls.certresolver=myresolver"
      #- "traefik.http.routers.phpmyadmin-secure.tls.options..minVersion=VersionTLS12"
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=PASSWORDSNIPSNIP

  mariadb:
    image: "mariadb"
    container_name: "mariadb"
    restart: unless-stopped
   # command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    ports:
      - "3306:3306"
    volumes:
      - /srv/mariadb/config:/var/lib/mysql:rw
     # - ./custom_mariadb/mariadb.cnf:/config/custom.cnf
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=PASSWORDSNIPSNIP
      - TZ=Europe/Amsterdam
      - MYSQL_DATABASE=mariadb
      - MYSQL_USER=mariadb
      - MYSQL_PASSWORD=PASSWORDSNIPSNIP
    labels:
      - "traefik.enable=true"


  php:
    image: "php:7.2-fpm"
    container_name: "php"
    expose:
      - 9000
    volumes:
      - /srv/www/portfolio/html:/srv/www/portfolio/html:z
      - /var/www/portfolio/php/php.ini:/usr/local/etc/php/php.ini
    labels:
      - "traefik.enable=true"

  nginx_portfolio_xyz:
    image: "nginx"
    container_name: "portfolio_xyz"
    restart: unless-stopped
   # environment:
    #  - NGINX_HOST=web.koen.link
     # - NGINX_PORT=80
    volumes:
      - /srv/www/portfolio/html:/srv/www/portfolio/html:z
      - /srv/www/portfolio/conf.d:/etc/nginx/conf.d
      - /etc/localtime:/etc/localtime
    depends_on:
      - php
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio_xyz.entrypoints=http"
      - "traefik.http.routers.portfolio_xyz.rule=Host(`koenjanssen.xyz`)"
      - "traefik.http.middlewares.portfolio_xyz-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.portfolio_xyz.middlewares=portfolio_xyz-https-redirect"
      - "traefik.http.routers.portfolio_xyz-secure.entrypoints=https"
      - "traefik.http.routers.portfolio_xyz-secure.rule=Host(`koenjanssen.xyz`)"
      - "traefik.http.routers.portfolio_xyz-secure.tls=true"
      - "traefik.http.routers.portfolio_xyz-secure.tls.certresolver=myresolver"
      - "traefik.http.routers.portfolio_xyz-secure.tls.domains[0].main=koenjanssen.xyz"
      - "traefik.http.routers.portfolio_xyz-secure.tls.domains[0].sans=*.koenjanssen.xyz"

  nc:
    image: "nextcloud"
    container_name: "nc"
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=PASSWORDSNIPSNIP
      - MYSQL_HOST=nc_db:3306
    volumes:
      - /srv/nc/nextcloud:/var/www/html:rw
      - /srv/nc/apps:/var/www/html/custom_apps:rw
      - /srv/nc/config:/var/www/html/config:rw
      - /srv/nc/data:/var/www/html/data:rw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nc.entrypoints=http"
      - "traefik.http.routers.nc.rule=Host(`nc.koen.link`)"
      - "traefik.http.middlewares.nc-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.nc.middlewares=nc-https-redirect"
      - "traefik.http.routers.nc-secure.entrypoints=https"
      - "traefik.http.routers.nc-secure.rule=Host(`nc.koen.link`)"
      - "traefik.http.middlewares.nc-rep.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nc-rep.redirectregex.replacement=https://$$1/remote.php/dav/"
      - "traefik.http.middlewares.nc-rep.redirectregex.permanent=true"
      - "traefik.http.middlewares.nc-header.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.routers.nextcloud-secure.middlewares=nc-rep,nc-header"
      - "traefik.http.routers.nc-secure.tls=true"
      - "traefik.http.routers.nc-secure.tls.certresolver=myresolver"


  nc_db:
    image: "mariadb"
    container_name: "nc_db"
    restart: unless-stopped
   # command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    volumes:
      - /srv/nc_db/config:/var/lib/mysql:rw
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=PASSWORDSNIPSNIP
      - TZ=Europe/Amsterdam
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=PASSWORDSNIPSNIP
    labels:
      - "traefik.enable=true"


  gitea-web:
    image: gitea/gitea:1.6
    restart: always
    volumes:
      - /srv/gitea/data/:/data
    expose:
      - "3000"
    ports:
      - "2222:22"
    depends_on:
      - gitea-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`git.koen.link`)"
      - "traefik.http.routers.gitea.entrypoints=http"
      - "traefik.http.middlewares.gitea-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.gitea.middlewares=gitea-https-redirect"
      - "traefik.http.routers.gitea-secure.entrypoints=https"
      - "traefik.http.routers.gitea-secure.rule=Host(`git.koen.link`)"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
      - "traefik.http.routers.gitea-secure.tls=true"
      - "traefik.http.routers.gitea-secure.tls.certresolver=myresolver"
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=gitea-db
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=PASSWORDSNIPSNIP
      - HTTP_PORT=3000

  gitea-db:
    image: mariadb:10
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=PASSWORDSNIPSNIP
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=PASSWORDSNIPSNIP
    volumes:
      - /srv/gitea/db/:/var/lib/mysql
    labels:
      - "traefik.enable=true"

  s2wad:
    image: "nginx"
    container_name: "s2wad"
    restart: unless-stopped
    volumes:
      - /srv/www/S2_WAD/html:/srv/www/S2_WAD/html
      - /srv/www/S2_WAD/conf.d:/etc/nginx/conf.d
      - /etc/localtime:/etc/localtime
    depends_on:
      - s2wad-php
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.s2wad.compress=true"
      - "traefik.http.routers.s2wad.entrypoints=http"
      - "traefik.http.routers.s2wad.rule=Host(`s2wad.koen.link`)"
      - "traefik.http.middlewares.s2wad-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.s2wad.middlewares=s2wad-https-redirect"
      - "traefik.http.routers.s2wad-secure.entrypoints=https"
      - "traefik.http.routers.s2wad-secure.rule=Host(`s2wad.koen.link`)"
      - "traefik.http.routers.s2wad-secure.tls=true"
      - "traefik.http.routers.s2wad-secure.tls.certresolver=myresolver"

  s2wad-php:
    image: "php:8.0.2-fpm"
    container_name: "s2wad-php"
    expose:
      - 9000
    volumes:
      - /srv/www/S2_WAD/html:/srv/www/S2_WAD/html
      - /var/www/S2_WAD/php/php.ini:/usr/local/etc/php/php.ini
    labels:
      - "traefik.enable=true"


  s2prj:
    image: "nginx"
    container_name: "s2prj"
    restart: unless-stopped
    volumes:
      - /srv/www/S2_PRJ/html:/srv/www/S2_PRJ/html
      - /srv/www/S2_PRJ/conf.d:/etc/nginx/conf.d
      - /etc/localtime:/etc/localtime
    depends_on:
      - s2prj-php
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.s2prj.compress=true"
      - "traefik.http.routers.s2prj.entrypoints=http"
      - "traefik.http.routers.s2prj.rule=Host(`s2prj.koen.link`)"
      - "traefik.http.middlewares.s2prj-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.s2prj.middlewares=s2wad-https-redirect"
      - "traefik.http.routers.s2prj-secure.entrypoints=https"
      - "traefik.http.routers.s2prj-secure.rule=Host(`s2prj.koen.link`)"
      - "traefik.http.routers.s2prj-secure.tls=true"
      - "traefik.http.routers.s2prj-secure.tls.certresolver=myresolver"

  s2prj-php:
    image: "php:8.0.2-fpm"
    container_name: "s2prj-php"
    expose:
      - 9000
    volumes:
      - /srv/www/S2_PRJ/html:/srv/www/S2_PRJ/html
      - /var/www/S2_PRJ/php/php.ini:/usr/local/etc/php/php.ini
    labels:
      - "traefik.enable=true"
